version: "3.8"
services: 
  server:
    depends_on:
      - db
    build: ./server
    command: npm run start
    environment:
      DB_HOST: db
      DB_NAME: hyperchat
      DB_USER: root
      DB_PWD: root
    ports: 
      - "8080:4000"
  client: 
    build: 
      context: ./client
      args: 
        REACT_APP_SERVER_HOST: localhost
        REACT_APP_SERVER_PORT: 8080
    command: npm run start:prod
    ports: 
      - "4000:4000"
  db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hyperchat
